version: '3.1'
services:

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password1
    ports:
      - "5432:5432"